import type { Metadata } from "next";
import "./globals.css";
import { RootProviders } from "@/app/providers/RootProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark h-screen text-foreground bg-background" suppressHydrationWarning>
      <body>
        
        <RootProviders>

          <main className="min-h-[calc(100vh-4rem-1px)]">
            
            <div className="relative pl-3 pr-3 h-auto py-3 z-10">
              {children}
            </div>
          
          </main>

        </RootProviders>
        
      </body>
    </html>
  );
}
